### ISSUE TITLE
`join-room` olayı kodlanmalı

### ISSUE THREAD

**Issue by saracalihan** [anchovycation/pingu-api#15]
Arayüzdeki doğrulama işlemlerini geçtikten sonra izleme sayfasına yönlendirilen kullanıcı bu olayı `emit` 'leyerek oda ile socket bağlantısı kurar.

```js
// Kullanıcı tarafı
socket.emit('join-room', {
  id: 1234
});
```
Sunucu gerekli işlemleri yaptıktan sonra `joined` olayını tetiklemeli ve kullanıcıya oda bilgisini göndermeli.
```js
// Sunucu tarafı
let room = await roomModel.findById(1234);
socket.join(1234) // socket oda bağlantısı yapılır
/* ilgili işlemler */
socket.emit('joined', room);
```
Kullanıcı `joined` olayı geldiğinda işlemin başarılı olduğunu anlar ve ilgili işlemleri yapar.

**Comment by beyzaerkan** [comment]
https://github.com/anchovycation/pingu-api/issues/17
