### ISSUE TITLE
Kullanıcı tipleri ve kurallar eklenmeli

### ISSUE THREAD

**Issue by saracalihan** [anchovycation/pingu-api#32]
+ Kullanıcılar tiplerine(admin, moderetor, guest, ...) göre işlem yapabilmeli.
+ Yapılacak işlemleri(video ekleme, video kaldırma, kullanıcıları odadan atma vb.) ve kullanıcı rollerini sadece yöneticiler değiştirmeli, odayı oluşturan otomatik olarak yönetici olmalı.

**Comment by beyzaerkan** [comment]
Roller
- O: Owner 
- M: Moderator
- G: Guest

Kurallar
- Video ekle / çıkar. (O - M -G)
- Video başlat / durdur. (O - M)
- Videoda herhangi bir yere atla. (O - M)
- Videoyu geç. (O - M)
- Playlistteki videoların yerlerini değiştir. (O - M)
- Mesaj yolla. (O - M - G)
- Kamera aç. (O - M - G)
- Kullanıcıyı odadan at. (O - M)
- Kullanıcı banla. (O - M - G)
