### ISSUE TITLE
MongoDb entegrasyonu yapılmalı

### ISSUE THREAD

**Issue by saracalihan** [anchovycation/pingu-api#59]
Redisin ana amacı hızlı erişilmesi gereken verileri cache'lemektir bundan dolayı oda ismi gibi sürekli güncellenmeyen verileri Redis yerine NoSQL'in sağladığı hızla Mongo'ya taşıyabiliriz. Herhangi bir ORM kullanmaktansa doğrudan mongonun client'ını kullanmak bir sıkıntı oluşturmayacağı kanaatindeyim.

### Redis:
Redis'te şunları tutabiliriz:

-  Mesajlar
- Video objesi 

Yine oda objesi ile bunları kullanmaya devam edebiliriz. Bu sayede diğer işlerimiz oldukça kolay olur.

### Mongo
- Kullanıcılar
- Playlist
- Oda bilgileri(isim, id, ...)

Buradaki Document ve collection yapısı da rediste kullandığımıza benzer olabilir bence.

Servisler içinde bazı yerlerde Mongo bazı verlerde Redis bazı yerlerde ise ikisi de ortak olarak kullanılabilecek bi yapı oluşturulmalı

@beyzaerkan  Sen ne düşünüyorsun bu konuda?

**Comment by beyzaerkan** [comment]
@saracalihan Sana katılıyorum, bazı durumlarda verilere direkt ulaşmak gerekebiliyor. Mongoya geçersek verilere erişmekte kolaylık sağlayabiliriz. Söylediğin gibi ORM kullanmak yerine `mongoose` modülünü kullanabiliriz.

**Comment by beyzaerkan** [comment]
@saracalihan Senin için de uygunsa bu görevi ben üstlenmek istiyorum.
